const biggestCities = [
    { city: "Tokyo", country: "Japan" },
    { city: "Delhi", country: "India" },
    { city: "Shanghai", country: "China" },
    { city: "São Paulo", country: "Brazil" },
    { city: "Mumbai", country: "India" },
    { city: "Mexico City", country: "Mexico" },
    { city: "Beijing", country: "China" },
    { city: "Osaka", country: "Japan" },
    { city: "Cairo", country: "Egypt" },
    { city: "New York City", country: "USA" },
    { city: "Dhaka", country: "Bangladesh" },
    { city: "Karachi", country: "Pakistan" },
    { city: "Buenos Aires", country: "Argentina" },
    { city: "Istanbul", country: "Turkey" },
    { city: "Chongqing", country: "China" },
    { city: "Kolkata", country: "India" },
    { city: "Manila", country: "Philippines" },
    { city: "Lagos", country: "Nigeria" },
    { city: "Rio de Janeiro", country: "Brazil" },
    { city: "Tianjin", country: "China" },
    { city: "Kinshasa", country: "Democratic Republic of the Congo" },
    { city: "Guangzhou", country: "China" },
    { city: "Los Angeles", country: "USA" },
    { city: "Moscow", country: "Russia" },
    { city: "Shenzhen", country: "China" },
    { city: "Lahore", country: "Pakistan" },
    { city: "Bangalore", country: "India" },
    { city: "Paris", country: "France" },
    { city: "Bogotá", country: "Colombia" },
    { city: "Jakarta", country: "Indonesia" },
    { city: "Chennai", country: "India" },
    { city: "Lima", country: "Peru" },
    { city: "Bangkok", country: "Thailand" },
    { city: "Hyderabad", country: "India" },
    { city: "London", country: "United Kingdom" },
    { city: "Tehran", country: "Iran" },
    { city: "Linyi", country: "China" },
    { city: "Chengdu", country: "China" },
    { city: "Nanjing", country: "China" },
    { city: "Wuhan", country: "China" },
    { city: "Ahmedabad", country: "India" },
    { city: "Kuala Lumpur", country: "Malaysia" },
    { city: "Xi'an", country: "China" },
    { city: "Hong Kong", country: "China" },
    { city: "Ho Chi Minh City", country: "Vietnam" },
    { city: "Surat", country: "India" },
    { city: "Dallas", country: "USA" },
    { city: "Shenyang", country: "China" },
    { city: "Santiago", country: "Chile" },
    { city: "Houston", country: "USA" },
    { city: "Philadelphia", country: "USA" },
    { city: "Belo Horizonte", country: "Brazil" },
    { city: "Madrid", country: "Spain" },
    { city: "Pune", country: "India" },
    { city: "Singapore", country: "Singapore" },
    { city: "Tunis", country: "Tunisia" },
    { city: "Suzhou", country: "China" },
    { city: "Incheon", country: "South Korea" },
    { city: "Essen", country: "Germany" },
    { city: "Guadalajara", country: "Mexico" },
    { city: "Durban", country: "South Africa" },
    { city: "Nagoya", country: "Japan" },
    { city: "Luanda", country: "Angola" },
    { city: "Rome", country: "Italy" },
    { city: "Houston", country: "USA" },
    { city: "Dalian", country: "China" },
    { city: "Kaohsiung", country: "Taiwan" },
    { city: "Medellín", country: "Colombia" },
    { city: "Cape Town", country: "South Africa" },
    { city: "San Francisco", country: "USA" },
    { city: "Johannesburg", country: "South Africa" },
    { city: "Kanpur", country: "India" },
    { city: "San Diego", country: "USA" },
    { city: "Hangzhou", country: "China" },
    { city: "Seattle", country: "USA" },
    { city: "Giza", country: "Egypt" },
    { city: "Berlin", country: "Germany" },
    { city: "Busan", country: "South Korea" },
    { city: "Athens", country: "Greece" },
    { city: "Sydney", country: "Australia" },
    { city: "Taipei", country: "Taiwan" },
    { city: "St. Louis", country: "USA" },
    { city: "Sapporo", country: "Japan" },
    { city: "Miami", country: "USA" },
    { city: "Surabaya", country: "Indonesia" },
    { city: "Abidjan", country: "Côte d'Ivoire" },
    { city: "Toronto", country: "Canada" },
    { city: "Dar es Salaam", country: "Tanzania" },
    { city: "Izmir", country: "Turkey" },
    { city: "Harbin", country: "China" },
    { city: "Ankara", country: "Turkey" },
    { city: "Jeddah", country: "Saudi Arabia" },
    { city: "Faisalabad", country: "Pakistan" },
    { city: "Brooklyn", country: "USA" },
    { city: "Daegu", country: "South Korea" },
    { city: "Addis Ababa", country: "Ethiopia" },
    { city: "Nairobi", country: "Kenya" },
];

const OPECcountries = [
    "Algeria",
    "Angola",
    "Ecuador",
    "Iran",
    "Iraq",
    "Kuwait",
    "Libya",
    "Nigeria",
    "Saudi Arabia",
    "United Arab Emirates",
    "Venezuela",
];

const beneluxCountries = ["Belgium", "Netherlands", "Luxembourg"];

const commonwealthCountries = [
    "Australia",
    "Bangladesh",
    "Canada",
    "India",
    "Malaysia",
    "Nigeria",
    "Pakistan",
    "Singapore",
    "United Kingdom",
];

const ASEANcountries = [
    "Brunei",
    "Cambodia",
    "Indonesia",
    "Laos",
    "Malaysia",
    "Myanmar",
    "Philippines",
    "Singapore",
    "Thailand",
    "Vietnam",
];

const nordicCountries = ["Denmark", "Finland", "Iceland", "Norway", "Sweden"];

const BRICScountries = ["Brazil", "Russia", "India", "China", "South Africa"];

const G7countries = [
    "Canada",
    "France",
    "Germany",
    "Italy",
    "Japan",
    "United Kingdom",
    "United States",
];

const middleEastCountries = [
    "Afghanistan",
    "Bahrain",
    "Cyprus",
    "Egypt",
    "Iran",
    "Iraq",
    "Israel",
    "Jordan",
    "Kuwait",
    "Lebanon",
    "Oman",
    "Palestine",
    "Qatar",
    "Saudi Arabia",
    "Syria",
    "Turkey",
    "United Arab Emirates",
    "Yemen",
];

const africanUnionMembers = [
    "Algeria",
    "Angola",
    "Benin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cameroon",
    "Central African Republic (CAR)",
    "Chad",
    "Comoros",
    "Democratic Republic of the Congo",
    "Republic of the Congo",
    "Cote d'Ivoire",
    "Djibouti",
    "Egypt",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini (formerly Swaziland)",
    "Ethiopia",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libya",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mauritius",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Rwanda",
    "Sao Tome and Principe",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Sudan",
    "Tanzania",
    "Togo",
    "Tunisia",
    "Uganda",
    "Zambia",
    "Zimbabwe",
];

const EUcountries = [
    "Austria",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Netherlands",
    "Poland",
    "Portugal",
    "Romania",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
];

const countries = [
    { country: "Afghanistan", capital: "Kabul" },
    { country: "Albania", capital: "Tirana" },
    { country: "Algeria", capital: "Algiers" },
    { country: "Andorra", capital: "Andorra la Vella" },
    { country: "Angola", capital: "Luanda" },
    { country: "Antigua and Barbuda", capital: "St. John's" },
    { country: "Argentina", capital: "Buenos Aires" },
    { country: "Armenia", capital: "Yerevan" },
    { country: "Australia", capital: "Canberra" },
    { country: "Austria", capital: "Vienna" },
    { country: "Azerbaijan", capital: "Baku" },
    { country: "Bahamas", capital: "Nassau" },
    { country: "Bahrain", capital: "Manama" },
    { country: "Bangladesh", capital: "Dhaka" },
    { country: "Barbados", capital: "Bridgetown" },
    { country: "Belarus", capital: "Minsk" },
    { country: "Belgium", capital: "Brussels" },
    { country: "Belize", capital: "Belmopan" },
    { country: "Benin", capital: "Porto-Novo" },
    { country: "Bhutan", capital: "Thimphu" },
    { country: "Bolivia", capital: "La Paz (administrative)" },
    { country: "Bosnia and Herzegovina", capital: "Sarajevo" },
    { country: "Botswana", capital: "Gaborone" },
    { country: "Brazil", capital: "Brasília" },
    { country: "Brunei", capital: "Bandar Seri Begawan" },
    { country: "Bulgaria", capital: "Sofia" },
    { country: "Burkina Faso", capital: "Ouagadougou" },
    { country: "Burundi", capital: "Gitega" },
    { country: "Cabo Verde", capital: "Praia" },
    { country: "Cambodia", capital: "Phnom Penh" },
    { country: "Cameroon", capital: "Yaoundé" },
    { country: "Canada", capital: "Ottawa" },
    { country: "Central African Republic", capital: "Bangui" },
    { country: "Chad", capital: "N'Djamena" },
    { country: "Chile", capital: "Santiago" },
    { country: "China", capital: "Beijing" },
    { country: "Colombia", capital: "Bogotá" },
    { country: "Comoros", capital: "Moroni" },
    { country: "Congo, Democratic Republic of the", capital: "Kinshasa" },
    { country: "Congo, Republic of the", capital: "Brazzaville" },
    { country: "Costa Rica", capital: "San José" },
    { country: "Côte d'Ivoire", capital: "Yamoussoukro" },
    { country: "Croatia", capital: "Zagreb" },
    { country: "Cuba", capital: "Havana" },
    { country: "Cyprus", capital: "Nicosia" },
    { country: "Czech Republic", capital: "Prague" },
    { country: "Denmark", capital: "Copenhagen" },
    { country: "Djibouti", capital: "Djibouti" },
    { country: "Dominica", capital: "Roseau" },
    { country: "Dominican Republic", capital: "Santo Domingo" },
    { country: "Ecuador", capital: "Quito" },
    { country: "Egypt", capital: "Cairo" },
    { country: "El Salvador", capital: "San Salvador" },
    { country: "Equatorial Guinea", capital: "Malabo" },
    { country: "Eritrea", capital: "Asmara" },
    { country: "Estonia", capital: "Tallinn" },
    { country: "Eswatini", capital: "Lobamba" },
    { country: "Ethiopia", capital: "Addis Ababa" },
    { country: "Fiji", capital: "Suva" },
    { country: "Finland", capital: "Helsinki" },
    { country: "France", capital: "Paris" },
    { country: "Gabon", capital: "Libreville" },
    { country: "Gambia", capital: "Banjul" },
    { country: "Georgia", capital: "Tbilisi" },
    { country: "Germany", capital: "Berlin" },
    { country: "Ghana", capital: "Accra" },
    { country: "Greece", capital: "Athens" },
    { country: "Grenada", capital: "St. George's" },
    { country: "Guatemala", capital: "Guatemala City" },
    { country: "Guinea", capital: "Conakry" },
    { country: "Guinea-Bissau", capital: "Bissau" },
    { country: "Guyana", capital: "Georgetown" },
    { country: "Haiti", capital: "Port-au-Prince" },
    { country: "Honduras", capital: "Tegucigalpa" },
    { country: "Hungary", capital: "Budapest" },
    { country: "Iceland", capital: "Reykjavik" },
    { country: "India", capital: "New Delhi" },
    { country: "Indonesia", capital: "Jakarta" },
    { country: "Iran", capital: "Tehran" },
    { country: "Iraq", capital: "Baghdad" },
    { country: "Ireland", capital: "Dublin" },
    { country: "Israel", capital: "Jerusalem" },
    { country: "Italy", capital: "Rome" },
    { country: "Jamaica", capital: "Kingston" },
    { country: "Japan", capital: "Tokyo" },
    { country: "Jordan", capital: "Amman" },
    { country: "Kazakhstan", capital: "Nur-Sultan" },
    { country: "Kenya", capital: "Nairobi" },
    { country: "Kiribati", capital: "South Tarawa" },
    { country: "Kuwait", capital: "Kuwait City" },
    { country: "Kyrgyzstan", capital: "Bishkek" },
    { country: "Laos", capital: "Vientiane" },
    { country: "Latvia", capital: "Riga" },
    { country: "Lebanon", capital: "Beirut" },
    { country: "Lesotho", capital: "Maseru" },
    { country: "Liberia", capital: "Monrovia" },
    { country: "Libya", capital: "Tripoli" },
    { country: "Liechtenstein", capital: "Vaduz" },
    { country: "Lithuania", capital: "Vilnius" },
    { country: "Luxembourg", capital: "Luxembourg City" },
    { country: "Madagascar", capital: "Antananarivo" },
    { country: "Malawi", capital: "Lilongwe" },
    { country: "Malaysia", capital: "Kuala Lumpur" },
    { country: "Maldives", capital: "Male" },
    { country: "Mali", capital: "Bamako" },
    { country: "Malta", capital: "Valletta" },
    { country: "Marshall Islands", capital: "Majuro" },
    { country: "Mauritania", capital: "Nouakchott" },
    { country: "Mauritius", capital: "Port Louis" },
    { country: "Mexico", capital: "Mexico City" },
    { country: "Micronesia, Federated States of", capital: "Palikir" },
    { country: "Moldova", capital: "Chisinau" },
    { country: "Monaco", capital: "Monaco" },
    { country: "Mongolia", capital: "Ulaanbaatar" },
    { country: "Montenegro", capital: "Podgorica" },
    { country: "Morocco", capital: "Rabat" },
    { country: "Mozambique", capital: "Maputo" },
    { country: "Myanmar", capital: "Nay Pyi Taw" },
    { country: "Namibia", capital: "Windhoek" },
    { country: "Nauru", capital: "Yaren District" },
    { country: "Nepal", capital: "Kathmandu" },
    { country: "Netherlands", capital: "Amsterdam" },
    { country: "New Zealand", capital: "Wellington" },
    { country: "Nicaragua", capital: "Managua" },
    { country: "Niger", capital: "Niamey" },
    { country: "Nigeria", capital: "Abuja" },
    { country: "North Korea", capital: "Pyongyang" },
    { country: "North Macedonia", capital: "Skopje" },
    { country: "Norway", capital: "Oslo" },
    { country: "Oman", capital: "Muscat" },
    { country: "Pakistan", capital: "Islamabad" },
    { country: "Palau", capital: "Ngerulmud" },
    { country: "Palestine", capital: "Ramallah" },
    { country: "Panama", capital: "Panama City" },
    { country: "Papua New Guinea", capital: "Port Moresby" },
    { country: "Paraguay", capital: "Asunción" },
    { country: "Peru", capital: "Lima" },
    { country: "Philippines", capital: "Manila" },
    { country: "Poland", capital: "Warsaw" },
    { country: "Portugal", capital: "Lisbon" },
    { country: "Qatar", capital: "Doha" },
    { country: "Romania", capital: "Bucharest" },
    { country: "Russia", capital: "Moscow" },
    { country: "Rwanda", capital: "Kigali" },
    { country: "Saint Kitts and Nevis", capital: "Basseterre" },
    { country: "Saint Lucia", capital: "Castries" },
    { country: "Saint Vincent and the Grenadines", capital: "Kingstown" },
    { country: "Samoa", capital: "Apia" },
    { country: "San Marino", capital: "San Marino" },
    { country: "Sao Tome and Principe", capital: "São Tomé" },
    { country: "Saudi Arabia", capital: "Riyadh" },
    { country: "Senegal", capital: "Dakar" },
    { country: "Serbia", capital: "Belgrade" },
    { country: "Seychelles", capital: "Victoria" },
    { country: "Sierra Leone", capital: "Freetown" },
    { country: "Singapore", capital: "Singapore" },
    { country: "Slovakia", capital: "Bratislava" },
    { country: "Slovenia", capital: "Ljubljana" },
    { country: "Solomon Islands", capital: "Honiara" },
    { country: "Somalia", capital: "Mogadishu" },
    {
        country: "South Africa",
        capital:
            "Pretoria (administrative); Cape Town (legislative); Bloemfontein (judicial)",
    },
    { country: "South Korea", capital: "Seoul" },
    { country: "South Sudan", capital: "Juba" },
    { country: "Spain", capital: "Madrid" },
    {
        country: "Sri Lanka",
        capital: "Sri Jayawardenepura Kotte (official); Colombo (commercial)",
    },
    { country: "Sudan", capital: "Khartoum" },
    { country: "Suriname", capital: "Paramaribo" },
    { country: "Sweden", capital: "Stockholm" },
    { country: "Switzerland", capital: "Bern" },
    { country: "Syria", capital: "Damascus" },
    { country: "Taiwan", capital: "Taipei" },
    { country: "Tajikistan", capital: "Dushanbe" },
    {
        country: "Tanzania",
        capital: "Dodoma (official); Dar es Salaam (commercial)",
    },
    { country: "Thailand", capital: "Bangkok" },
    { country: "Timor-Leste", capital: "Dili" },
    { country: "Togo", capital: "Lomé" },
    { country: "Tonga", capital: "Nuku'alofa" },
    { country: "Trinidad and Tobago", capital: "Port of Spain" },
    { country: "Tunisia", capital: "Tunis" },
    { country: "Turkey", capital: "Ankara" },
    { country: "Turkmenistan", capital: "Ashgabat" },
    { country: "Tuvalu", capital: "Funafuti" },
    { country: "Uganda", capital: "Kampala" },
    { country: "Ukraine", capital: "Kyiv (Kiev)" },
    { country: "United Arab Emirates", capital: "Abu Dhabi" },
    { country: "United Kingdom", capital: "London" },
    { country: "United States", capital: "Washington, D.C." },
    { country: "Uruguay", capital: "Montevideo" },
    { country: "Uzbekistan", capital: "Tashkent" },
    { country: "Vanuatu", capital: "Port Vila" },
    { country: "Vatican City (Holy See)", capital: "Vatican City" },
    { country: "Venezuela", capital: "Caracas" },
    { country: "Vietnam", capital: "Hanoi" },
    { country: "Yemen", capital: "Sana'a" },
    { country: "Zambia", capital: "Lusaka" },
    { country: "Zimbabwe", capital: "Harare" },
];
